### YamlMime:ManagedReference
items:
- uid: NPCEngine.NPCEngineConfig
  commentId: T:NPCEngine.NPCEngineConfig
  id: NPCEngineConfig
  parent: NPCEngine
  children:
  - NPCEngine.NPCEngineConfig.connectToExistingServer
  - NPCEngine.NPCEngineConfig.debugLogs
  - NPCEngine.NPCEngineConfig.modelsPath
  - NPCEngine.NPCEngineConfig.nChunksSpeechGeneration
  - NPCEngine.NPCEngineConfig.npcEnginePath
  - NPCEngine.NPCEngineConfig.Port
  - NPCEngine.NPCEngineConfig.RefreshServices
  - NPCEngine.NPCEngineConfig.serverAddress
  - NPCEngine.NPCEngineConfig.serverConsole
  - NPCEngine.NPCEngineConfig.serverType
  - NPCEngine.NPCEngineConfig.services
  - NPCEngine.NPCEngineConfig.ToBeStarted(System.String)
  langs:
  - csharp
  - vb
  name: NPCEngineConfig
  nameWithType: NPCEngineConfig
  fullName: NPCEngine.NPCEngineConfig
  type: Class
  source:
    id: NPCEngineConfig
    path: ''
    startLine: 521
  assemblies:
  - cs.temp.dll
  namespace: NPCEngine
  syntax:
    content: 'public class NPCEngineConfig : Singleton<NPCEngineConfig>'
    content.vb: >-
      Public Class NPCEngineConfig

          Inherits Singleton(Of NPCEngineConfig)
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: NPCEngine.NPCEngineConfig.services
  commentId: F:NPCEngine.NPCEngineConfig.services
  id: services
  parent: NPCEngine.NPCEngineConfig
  langs:
  - csharp
  - vb
  name: services
  nameWithType: NPCEngineConfig.services
  fullName: NPCEngine.NPCEngineConfig.services
  type: Field
  source:
    id: services
    path: ''
    startLine: 529
  assemblies:
  - cs.temp.dll
  namespace: NPCEngine
  syntax:
    content: public List<ServiceConfigDescriptor> services
    return:
      type: System.Collections.Generic.List{NPCEngine.ServiceConfigDescriptor}
    content.vb: Public services As List(Of ServiceConfigDescriptor)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: NPCEngine.NPCEngineConfig.serverType
  commentId: F:NPCEngine.NPCEngineConfig.serverType
  id: serverType
  parent: NPCEngine.NPCEngineConfig
  langs:
  - csharp
  - vb
  name: serverType
  nameWithType: NPCEngineConfig.serverType
  fullName: NPCEngine.NPCEngineConfig.serverType
  type: Field
  source:
    id: serverType
    path: ''
    startLine: 531
  assemblies:
  - cs.temp.dll
  namespace: NPCEngine
  syntax:
    content: public ServerType serverType
    return:
      type: Global.ServerType
    content.vb: Public serverType As ServerType
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: NPCEngine.NPCEngineConfig.serverAddress
  commentId: F:NPCEngine.NPCEngineConfig.serverAddress
  id: serverAddress
  parent: NPCEngine.NPCEngineConfig
  langs:
  - csharp
  - vb
  name: serverAddress
  nameWithType: NPCEngineConfig.serverAddress
  fullName: NPCEngine.NPCEngineConfig.serverAddress
  type: Field
  source:
    id: serverAddress
    path: ''
    startLine: 533
  assemblies:
  - cs.temp.dll
  namespace: NPCEngine
  syntax:
    content: public string serverAddress
    return:
      type: System.String
    content.vb: Public serverAddress As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: NPCEngine.NPCEngineConfig.Port
  commentId: P:NPCEngine.NPCEngineConfig.Port
  id: Port
  parent: NPCEngine.NPCEngineConfig
  langs:
  - csharp
  - vb
  name: Port
  nameWithType: NPCEngineConfig.Port
  fullName: NPCEngine.NPCEngineConfig.Port
  type: Property
  source:
    id: Port
    path: ''
    startLine: 535
  assemblies:
  - cs.temp.dll
  namespace: NPCEngine
  syntax:
    content: public string Port { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Port As String
  overload: NPCEngine.NPCEngineConfig.Port*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: NPCEngine.NPCEngineConfig.modelsPath
  commentId: F:NPCEngine.NPCEngineConfig.modelsPath
  id: modelsPath
  parent: NPCEngine.NPCEngineConfig
  langs:
  - csharp
  - vb
  name: modelsPath
  nameWithType: NPCEngineConfig.modelsPath
  fullName: NPCEngine.NPCEngineConfig.modelsPath
  type: Field
  source:
    id: modelsPath
    path: ''
    startLine: 544
  assemblies:
  - cs.temp.dll
  namespace: NPCEngine
  syntax:
    content: public string modelsPath
    return:
      type: System.String
    content.vb: Public modelsPath As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: NPCEngine.NPCEngineConfig.npcEnginePath
  commentId: F:NPCEngine.NPCEngineConfig.npcEnginePath
  id: npcEnginePath
  parent: NPCEngine.NPCEngineConfig
  langs:
  - csharp
  - vb
  name: npcEnginePath
  nameWithType: NPCEngineConfig.npcEnginePath
  fullName: NPCEngine.NPCEngineConfig.npcEnginePath
  type: Field
  source:
    id: npcEnginePath
    path: ''
    startLine: 547
  assemblies:
  - cs.temp.dll
  namespace: NPCEngine
  syntax:
    content: public string npcEnginePath
    return:
      type: System.String
    content.vb: Public npcEnginePath As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: NPCEngine.NPCEngineConfig.debugLogs
  commentId: F:NPCEngine.NPCEngineConfig.debugLogs
  id: debugLogs
  parent: NPCEngine.NPCEngineConfig
  langs:
  - csharp
  - vb
  name: debugLogs
  nameWithType: NPCEngineConfig.debugLogs
  fullName: NPCEngine.NPCEngineConfig.debugLogs
  type: Field
  source:
    id: debugLogs
    path: ''
    startLine: 549
  assemblies:
  - cs.temp.dll
  namespace: NPCEngine
  syntax:
    content: public bool debugLogs
    return:
      type: System.Boolean
    content.vb: Public debugLogs As Boolean
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: NPCEngine.NPCEngineConfig.serverConsole
  commentId: F:NPCEngine.NPCEngineConfig.serverConsole
  id: serverConsole
  parent: NPCEngine.NPCEngineConfig
  langs:
  - csharp
  - vb
  name: serverConsole
  nameWithType: NPCEngineConfig.serverConsole
  fullName: NPCEngine.NPCEngineConfig.serverConsole
  type: Field
  source:
    id: serverConsole
    path: ''
    startLine: 550
  assemblies:
  - cs.temp.dll
  namespace: NPCEngine
  syntax:
    content: public bool serverConsole
    return:
      type: System.Boolean
    content.vb: Public serverConsole As Boolean
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: NPCEngine.NPCEngineConfig.connectToExistingServer
  commentId: F:NPCEngine.NPCEngineConfig.connectToExistingServer
  id: connectToExistingServer
  parent: NPCEngine.NPCEngineConfig
  langs:
  - csharp
  - vb
  name: connectToExistingServer
  nameWithType: NPCEngineConfig.connectToExistingServer
  fullName: NPCEngine.NPCEngineConfig.connectToExistingServer
  type: Field
  source:
    id: connectToExistingServer
    path: ''
    startLine: 551
  assemblies:
  - cs.temp.dll
  namespace: NPCEngine
  syntax:
    content: public bool connectToExistingServer
    return:
      type: System.Boolean
    content.vb: Public connectToExistingServer As Boolean
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: NPCEngine.NPCEngineConfig.nChunksSpeechGeneration
  commentId: F:NPCEngine.NPCEngineConfig.nChunksSpeechGeneration
  id: nChunksSpeechGeneration
  parent: NPCEngine.NPCEngineConfig
  langs:
  - csharp
  - vb
  name: nChunksSpeechGeneration
  nameWithType: NPCEngineConfig.nChunksSpeechGeneration
  fullName: NPCEngine.NPCEngineConfig.nChunksSpeechGeneration
  type: Field
  source:
    id: nChunksSpeechGeneration
    path: ''
    startLine: 554
  assemblies:
  - cs.temp.dll
  namespace: NPCEngine
  syntax:
    content: public int nChunksSpeechGeneration
    return:
      type: System.Int32
    content.vb: Public nChunksSpeechGeneration As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: NPCEngine.NPCEngineConfig.ToBeStarted(System.String)
  commentId: M:NPCEngine.NPCEngineConfig.ToBeStarted(System.String)
  id: ToBeStarted(System.String)
  parent: NPCEngine.NPCEngineConfig
  langs:
  - csharp
  - vb
  name: ToBeStarted(String)
  nameWithType: NPCEngineConfig.ToBeStarted(String)
  fullName: NPCEngine.NPCEngineConfig.ToBeStarted(System.String)
  type: Method
  source:
    id: ToBeStarted
    path: ''
    startLine: 565
  assemblies:
  - cs.temp.dll
  namespace: NPCEngine
  syntax:
    content: public bool ToBeStarted(string name)
    parameters:
    - id: name
      type: System.String
    return:
      type: System.Boolean
    content.vb: Public Function ToBeStarted(name As String) As Boolean
  overload: NPCEngine.NPCEngineConfig.ToBeStarted*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: NPCEngine.NPCEngineConfig.RefreshServices
  commentId: M:NPCEngine.NPCEngineConfig.RefreshServices
  id: RefreshServices
  parent: NPCEngine.NPCEngineConfig
  langs:
  - csharp
  - vb
  name: RefreshServices()
  nameWithType: NPCEngineConfig.RefreshServices()
  fullName: NPCEngine.NPCEngineConfig.RefreshServices()
  type: Method
  source:
    id: RefreshServices
    path: ''
    startLine: 583
  assemblies:
  - cs.temp.dll
  namespace: NPCEngine
  syntax:
    content: public void RefreshServices()
    content.vb: Public Sub RefreshServices
  overload: NPCEngine.NPCEngineConfig.RefreshServices*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: NPCEngine
  commentId: N:NPCEngine
  name: NPCEngine
  nameWithType: NPCEngine
  fullName: NPCEngine
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Collections.Generic.List{NPCEngine.ServiceConfigDescriptor}
  commentId: T:System.Collections.Generic.List{NPCEngine.ServiceConfigDescriptor}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  name: List<ServiceConfigDescriptor>
  nameWithType: List<ServiceConfigDescriptor>
  fullName: System.Collections.Generic.List<NPCEngine.ServiceConfigDescriptor>
  nameWithType.vb: List(Of ServiceConfigDescriptor)
  fullName.vb: System.Collections.Generic.List(Of NPCEngine.ServiceConfigDescriptor)
  name.vb: List(Of ServiceConfigDescriptor)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: NPCEngine.ServiceConfigDescriptor
    name: ServiceConfigDescriptor
    nameWithType: ServiceConfigDescriptor
    fullName: NPCEngine.ServiceConfigDescriptor
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: NPCEngine.ServiceConfigDescriptor
    name: ServiceConfigDescriptor
    nameWithType: ServiceConfigDescriptor
    fullName: NPCEngine.ServiceConfigDescriptor
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: Global.ServerType
  commentId: '!:Global.ServerType'
  isExternal: true
  name: ServerType
  nameWithType: ServerType
  fullName: ServerType
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: NPCEngine.NPCEngineConfig.Port*
  commentId: Overload:NPCEngine.NPCEngineConfig.Port
  name: Port
  nameWithType: NPCEngineConfig.Port
  fullName: NPCEngine.NPCEngineConfig.Port
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: NPCEngine.NPCEngineConfig.ToBeStarted*
  commentId: Overload:NPCEngine.NPCEngineConfig.ToBeStarted
  name: ToBeStarted
  nameWithType: NPCEngineConfig.ToBeStarted
  fullName: NPCEngine.NPCEngineConfig.ToBeStarted
- uid: NPCEngine.NPCEngineConfig.RefreshServices*
  commentId: Overload:NPCEngine.NPCEngineConfig.RefreshServices
  name: RefreshServices
  nameWithType: NPCEngineConfig.RefreshServices
  fullName: NPCEngine.NPCEngineConfig.RefreshServices
