### YamlMime:ManagedReference
items:
- uid: NPCEngine.NPCEngineConfigEditor
  commentId: T:NPCEngine.NPCEngineConfigEditor
  id: NPCEngineConfigEditor
  parent: NPCEngine
  children:
  - NPCEngine.NPCEngineConfigEditor.OnInspectorGUI
  langs:
  - csharp
  - vb
  name: NPCEngineConfigEditor
  nameWithType: NPCEngineConfigEditor
  fullName: NPCEngine.NPCEngineConfigEditor
  type: Class
  source:
    id: NPCEngineConfigEditor
    path: ''
    startLine: 3024
  assemblies:
  - cs.temp.dll
  namespace: NPCEngine
  syntax:
    content: 'public class NPCEngineConfigEditor : Editor'
    content.vb: >-
      Public Class NPCEngineConfigEditor
          Inherits Editor
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: NPCEngine.NPCEngineConfigEditor.OnInspectorGUI
  commentId: M:NPCEngine.NPCEngineConfigEditor.OnInspectorGUI
  id: OnInspectorGUI
  parent: NPCEngine.NPCEngineConfigEditor
  langs:
  - csharp
  - vb
  name: OnInspectorGUI()
  nameWithType: NPCEngineConfigEditor.OnInspectorGUI()
  fullName: NPCEngine.NPCEngineConfigEditor.OnInspectorGUI()
  type: Method
  source:
    id: OnInspectorGUI
    path: ''
    startLine: 3031
  assemblies:
  - cs.temp.dll
  namespace: NPCEngine
  syntax:
    content: public override void OnInspectorGUI()
    content.vb: Public Overrides Sub OnInspectorGUI
  overload: NPCEngine.NPCEngineConfigEditor.OnInspectorGUI*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: NPCEngine
  commentId: N:NPCEngine
  name: NPCEngine
  nameWithType: NPCEngine
  fullName: NPCEngine
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: NPCEngine.NPCEngineConfigEditor.OnInspectorGUI*
  commentId: Overload:NPCEngine.NPCEngineConfigEditor.OnInspectorGUI
  name: OnInspectorGUI
  nameWithType: NPCEngineConfigEditor.OnInspectorGUI
  fullName: NPCEngine.NPCEngineConfigEditor.OnInspectorGUI
